spring:
  application:
    name: EXPORT_EXCEL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/excel
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true